service:
  name: SelectQuery

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  # customize based on expected data volumes
  memorySize: 512
  timeout: 15
  # modify the IAM role below for more customization
  dataBucket: selectquery-data

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}

  environment:
    RESULT_BUCKET_NAME:
      Ref: ResultsBucket

  tracing:
    lambda: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [ResultsBucket, Arn]
              - "*"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::${self:custom.dataBucket}/*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        Fn::Join:
          - ":"
          - - arn:aws:lambda
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - function
            - ${self:service.name}-${self:provider.stage}-worker

  memorySize: ${self:custom.memorySize}
  timeout: ${self:custom.timeout}

package:
  artifact: artifacts/lambda.zip

functions:
  distributor:
    handler: SelectQuery.Lambda::SelectQuery.Lambda.DistributorEntryPoint::Handler
    environment:
      WORKER_FUNCTION_NAME:
        Ref: WorkerLambdaFunction
  worker:
    handler: SelectQuery.Lambda::SelectQuery.Lambda.WorkerEntryPoint::Handler

resources:
  Resources:
    ResultsBucket:
      Type: AWS::S3::Bucket
