name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=1.0.${{github.run_number}}
    - name: Package
      run: |
        dotnet pack SelectParser/SelectParser.csproj --configuration Release --no-build -o artifacts/ -p:PackageVersion=1.0.${{github.run_number}}
        dotnet pack SelectQuery.Evaluation/SelectQuery.Evaluation.csproj --configuration Release --no-build -o artifacts/ -p:PackageVersion=1.0.${{github.run_number}}
    - name: Push
      run: |
        dotnet nuget push ./artifacts/SelectParser.*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ./artifacts/SelectQuery.Evaluation.*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
